export const filters = [
	{
		catalog_image_url:
			'https://static.lenskart.com/media//wysiwyg//ic_catalogue_frame_color.png',
		filter_image_url:
			'https://static.lenskart.com/media//wysiwyg//ic_filter_frame_color.png',
		id: 'frame_color_id',
		name: 'Frame Color',
		options: [
			{
				title: 'Black',
				id: '13323',
				no_of_products: 97,
				hex_code: '',
				sort_order: 0,
			},
			{
				title: 'Blue',
				id: '13324',
				no_of_products: 46,
				hex_code: '',
				sort_order: 0,
			},
			{
				title: 'Brown',
				id: '13325',
				no_of_products: 45,
				hex_code: '',
				sort_order: 0,
			},
			{
				title: 'Gunmetal',
				id: '16016',
				no_of_products: 39,
				hex_code: '',
				sort_order: 0,
			},
			{
				title: 'Gold',
				id: '23471',
				no_of_products: 31,
				sort_order: 0,
			},
			{
				title: 'Gold',
				id: '23471',
				no_of_products: 31,
				hex_code: '',
				sort_order: 0,
			},
			{
				title: 'Tortoise',
				id: '18029',
				no_of_products: 26,
				hex_code: '',
				sort_order: 0,
			},
			{
				title: 'Silver',
				id: '13332',
				no_of_products: 18,
				hex_code: '',
				sort_order: 0,
			},
			{
				title: 'Green',
				id: '13327',
				no_of_products: 10,
				hex_code: '',
				sort_order: 0,
			},
			{
				title: 'Grey',
				id: '13328',
				no_of_products: 10,
				hex_code: '',
				sort_order: 0,
			},
			{
				title: 'Pink',
				id: '13330',
				no_of_products: 8,
				hex_code: '',
				sort_order: 0,
			},
			{
				title: 'Transparent',
				id: '14417',
				no_of_products: 8,
				hex_code: '',
				sort_order: 0,
			},
			{
				title: 'Purple',
				id: '16065',
				no_of_products: 8,
				hex_code: '',
				sort_order: 0,
			},
			{
				title: 'Copper',
				id: '16415',
				no_of_products: 6,
				hex_code: '',
				sort_order: 0,
			},
			{
				title: 'Maroon',
				id: '18701',
				no_of_products: 6,
				hex_code: '',
				sort_order: 0,
			},
			{
				title: 'Red',
				id: '13331',
				no_of_products: 3,
				hex_code: '',
				sort_order: 0,
			},
			{
				title: 'Yellow',
				id: '13334',
				no_of_products: 3,
				hex_code: '',
				sort_order: 0,
			},
			{
				title: 'Violet',
				id: '18700',
				no_of_products: 1,
				hex_code: '',
				sort_order: 0,
			},
		],
	},
	{
		catalog_image_url:
			'https://static1.lenskart.com/media//wysiwyg//ic_catalogue_brands.png',
		filter_image_url:
			'https://static.lenskart.com/media//wysiwyg//ic_filter_brand.png',
		id: 'brandname_id',
		name: 'Brands',
		options: [
			{
				title: 'Vincent Chase',
				id: '10733',
				no_of_products: 365,
				sort_order: 0,
				displayTitle: 'Vincent Chase',
			},
			{
				title: 'Lenskart Air',
				id: '22563',
				no_of_products: 179,
				sort_order: 0,
				displayTitle: 'Lenskart Air',
			},
			{
				title: 'Vincent Chase VC',
				id: '21861',
				no_of_products: 53,
				sort_order: 0,
				displayTitle: 'Vincent Chase VC',
			},
		],
		listUnitType: 'filter',
		hideFilters: [],
	},
	{
		catalog_image_url:
			'https://static.lenskart.com/media//wysiwyg//ic_catalogue_frame_size.png',
		filter_image_url:
			'https://static1.lenskart.com/media//wysiwyg//ic_filter_frame_size.png',
		id: 'frame_size_id',
		name: 'Frame Size',
		options: [
			{
				title: 'Extra Narrow',
				id: '23559',
				no_of_products: 21,
				sort_order: 0,
				displayTitle: 'Extra Narrow',
			},
			{
				title: 'Narrow',
				id: '23557',
				no_of_products: 81,
				sort_order: 1,
				displayTitle: 'Narrow',
			},
			{
				title: 'Small',
				id: '11342',
				no_of_products: 1,
				image_url:
					'https://static1.lenskart.com/media/desktop/img/Dec20/app/Size/Small.png',
				sort_order: 2,
				displayTitle: 'Small',
			},
			{
				title: 'Medium',
				id: '11341',
				no_of_products: 149,
				image_url:
					'https://static1.lenskart.com/media/desktop/img/Dec20/app/Size/Medium.png',
				sort_order: 4,
				displayTitle: 'Medium',
			},
			{
				title: 'Wide',
				id: '23555',
				no_of_products: 91,
				sort_order: 6,
				displayTitle: 'Wide',
			},
			{
				title: 'Extra Wide',
				id: '23553',
				no_of_products: 22,
				sort_order: 7,
				displayTitle: 'Extra Wide',
			},
		],
		listUnitType: 'filter',
		hideFilters: [],
	},
	{
		catalog_image_url:
			'https://static.lenskart.com/media//wysiwyg//ic_catalogue_price.png',
		filter_image_url:
			'https://static.lenskart.com/media//wysiwyg//ic_filter_price.png',
		id: 'lenskart_price',
		name: 'Price',
		options: [
			{
				title: 'Rs. 0 - Rs. 999',
				id: '0',
				no_of_products: 286,
				sort_order: 0,
				displayTitle: '₹ 0 - ₹ 999',
			},
			{
				title: 'Rs. 1000 - Rs. 1999',
				id: '1',
				no_of_products: 79,
				sort_order: 0,
				displayTitle: '₹ 1000 - ₹ 1999',
			},
		],
		listUnitType: 'filter',
		hideFilters: [],
	},
	{
		catalog_image_url:
			'https://static.lenskart.com/media//wysiwyg//ic_catalogue_gender.png',
		filter_image_url:
			'https://static1.lenskart.com/media//wysiwyg//ic_filter_gender.png',
		id: 'gender_id',
		name: 'Gender',
		options: [
			{
				title: 'Unisex',
				id: '10528',
				no_of_products: 303,
				sort_order: 0,
				displayTitle: 'Unisex',
			},
			{
				title: 'Women',
				id: '10529',
				no_of_products: 62,
				sort_order: 0,
				displayTitle: 'Women',
			},
		],
		listUnitType: 'filter',
		hideFilters: [],
	},
	{
		catalog_image_url:
			'https://static.lenskart.com/media//wysiwyg//ic_filter_frame_material.png',
		filter_image_url:
			'https://static1.lenskart.com/media//wysiwyg//ic_catalogue_frame_material.png',
		id: 'material_id',
		name: 'Material',
		options: [
			{
				title: 'Stainless Steel (Simple Matte & Shiny)',
				id: '17005',
				no_of_products: 201,
				sort_order: 0,
				displayTitle: 'Stainless Steel (Simple Matte...',
			},
			{
				title: 'Acetate (Vintage Regular)',
				id: '17007',
				no_of_products: 127,
				sort_order: 0,
				displayTitle: 'Acetate (Vintage Regular)',
			},
			{
				title: 'TR90 (Flexible Light-Weight)',
				id: '17008',
				no_of_products: 4,
				sort_order: 0,
				displayTitle: 'TR90 (Flexible Light-Weight)',
			},
		],
		listUnitType: 'filter',
		hideFilters: [],
	},
	{
		catalog_image_url:
			'https://static1.lenskart.com/media//wysiwyg//ic_catalogue_weight_group.png',
		filter_image_url:
			'https://static.lenskart.com/media//wysiwyg//ic_filter_weight_group.png',
		id: 'frame_weight_group_id',
		name: 'Weight Group',
		options: [
			{
				title: 'Light',
				id: '14109',
				no_of_products: 224,
				sort_order: 0,
				displayTitle: 'Light',
			},
			{
				title: 'Average',
				id: '14110',
				no_of_products: 106,
				sort_order: 0,
				displayTitle: 'Average',
			},
		],
		listUnitType: 'filter',
		hideFilters: [],
	},
	{
		catalog_image_url:
			'https://static2.lenskart.com/media//wysiwyg//ic_catalogue_prescription_type.png',
		filter_image_url:
			'https://static2.lenskart.com/media//wysiwyg//ic_filter_prescription_type.png',
		id: 'prescription_type_id',
		name: 'Prescription Type',
		options: [
			{
				title: 'Bifocal / Progressive Supported',
				id: '10620',
				no_of_products: 365,
				sort_order: 0,
				displayTitle: 'Bifocal / Progressive Supported',
			},
		],
		listUnitType: 'filter',
		hideFilters: [],
	},
	{
		catalog_image_url:
			'https://static2.lenskart.com/media//wysiwyg//ic_catalogue_offer_name.png',
		filter_image_url:
			'https://static.lenskart.com/media//wysiwyg//ic_filter_offer_name.png',
		id: 'supported_powers_id',
		name: 'Supported Powers',
		options: [
			{
				title: 'Upto Low Power',
				id: '11',
				no_of_products: 364,
				sort_order: 1,
				displayTitle: 'Upto Low Power',
			},
			{
				title: 'Upto Medium Power',
				id: '12',
				no_of_products: 364,
				sort_order: 3,
				displayTitle: 'Upto Medium Power',
			},
		],
		detailsInfo: {
			url: 'https://www.lenskart.com/power-for-eyeglasses',
			label: 'Know your Power Type',
		},
		listUnitType: 'filter',
		hideFilters: [],
	},
	{
		catalog_image_url:
			'https://static2.lenskart.com/media//wysiwyg//ic_catalogue_collections.png',
		filter_image_url:
			'https://static1.lenskart.com/media//wysiwyg//ic_filter_collection.png',
		id: 'sub_brand_id',
		name: 'Collection',
		options: [
			{
				title: 'HD Acetate',
				id: '22287',
				no_of_products: 20,
				sort_order: 0,
				displayTitle: 'HD Acetate',
			},
		],
		listUnitType: 'filter',
		hideFilters: [],
	},
	{
		catalog_image_url:
			'https://static2.lenskart.com/media//wysiwyg//ic_catalogue_frame_width.png',
		filter_image_url:
			'https://static2.lenskart.com/media//wysiwyg//ic_filter_frame_width.png',
		id: 'frame_width_id',
		name: 'Frame Width',
		options: [
			{
				title: '126 mm',
				id: '22739',
				no_of_products: 2,
				sort_order: 12,
				displayTitle: '126 mm',
			},
			{
				title: '127 mm',
				id: '22738',
				no_of_products: 2,
				sort_order: 13,
				displayTitle: '127 mm',
			},
			{
				title: '128 mm',
				id: '22737',
				no_of_products: 3,
				sort_order: 14,
				displayTitle: '128 mm',
			},
			{
				title: '129 mm',
				id: '22736',
				no_of_products: 14,
				sort_order: 15,
				displayTitle: '129 mm',
			},
			{
				title: '130 mm',
				id: '22735',
				no_of_products: 11,
				sort_order: 16,
				displayTitle: '130 mm',
			},
			{
				title: '131 mm',
				id: '22734',
				no_of_products: 17,
				sort_order: 17,
				displayTitle: '131 mm',
			},
			{
				title: '132 mm',
				id: '22733',
				no_of_products: 33,
				sort_order: 18,
				displayTitle: '132 mm',
			},
			{
				title: '133 mm',
				id: '22732',
				no_of_products: 25,
				sort_order: 19,
				displayTitle: '133 mm',
			},
			{
				title: '134 mm',
				id: '22731',
				no_of_products: 23,
				sort_order: 20,
				displayTitle: '134 mm',
			},
			{
				title: '135 mm',
				id: '22730',
				no_of_products: 45,
				sort_order: 21,
				displayTitle: '135 mm',
			},
			{
				title: '136 mm',
				id: '22729',
				no_of_products: 59,
				sort_order: 22,
				displayTitle: '136 mm',
			},
			{
				title: '137 mm',
				id: '22728',
				no_of_products: 20,
				sort_order: 23,
				displayTitle: '137 mm',
			},
			{
				title: '138 mm',
				id: '22727',
				no_of_products: 30,
				sort_order: 24,
				displayTitle: '138 mm',
			},
			{
				title: '139 mm',
				id: '22726',
				no_of_products: 27,
				sort_order: 25,
				displayTitle: '139 mm',
			},
			{
				title: '140 mm',
				id: '22725',
				no_of_products: 28,
				sort_order: 26,
				displayTitle: '140 mm',
			},
			{
				title: '141 mm',
				id: '22724',
				no_of_products: 6,
				sort_order: 27,
				displayTitle: '141 mm',
			},
			{
				title: '142 mm',
				id: '22723',
				no_of_products: 13,
				sort_order: 28,
				displayTitle: '142 mm',
			},
			{
				title: '143 mm',
				id: '22722',
				no_of_products: 3,
				sort_order: 29,
				displayTitle: '143 mm',
			},
			{
				title: '144 mm',
				id: '22721',
				no_of_products: 4,
				sort_order: 30,
				displayTitle: '144 mm',
			},
		],
		listUnitType: 'filter',
		hideFilters: [],
	},
]
